return {

	Name = '2025.06.02.1', -- Name of the version (yyyy.mm.dd.canidate_#)
	Description = 'July 2nd, 2025 release of MXV2. Candidate 1', -- Describe the version's name here
	VersionNumber = 10, -- The specified version number for this release
	Key = '', -- Key used to use this version, should it be locked. Leave as '' to unlock this version.
	Notes = {
		Comments = { -- Addition/implementation, removal, and more comments go here.
			'Adds the ability for Light classes to work in the Light parts in buttons.',
			'Implements nudge signal loop audio.'
		},
		Patches = { -- Patches (i.e. bug fixes, important adjustments, etc.) go here.
			
		},
	},

}