return {

	Name = 'MV2_2025_2', -- Name of the version (MV2_yyyy_release candiate #)
	Description = 'January 31st, 2025 release of MXV2. Candidate 2', -- Describe the version's name here
	VersionNumber = 7, -- The specified version number for this release
	Key = '', -- Key used to use this version, should it be locked. Leave as '' to unlock this version.
	Notes = {
		Comments = { -- Addition/implementation, removal, and more comments go here.
			'Add floor side support.',
		},
		Patches = { -- Patches (i.e. bug fixes, important adjustments, etc.) go here.
			
		},
	},

}