return {

	Name = '25_09_2024_1', -- Name of the version (dd_mm_yyyy_version number)
	Description = 'September 25th, 2024 release.', -- Describe the version's name here
	VersionNumber = 1, -- The specified version number for this release
	Key = '', -- Key used to use this version, should it be locked. Leave as '' to unlock this version.
	Notes = {
		Comments = { -- Miscallaneous comments go here.
			'Initial release version.',
		},
		Patches = { -- Patches (i.e. bug fixes, important adjustments, etc.) go here.
			''
		},
	},

}