return {

	Name = '2025.06.02.EX1', -- Name of the version (yyyy.mm.dd.canidate_#)
	Description = 'July 2nd, 2025 release of MXV2. EXPERIMENTAL Candidate 1', -- Describe the version's name here
	VersionNumber = 11, -- The specified version number for this release
	Key = 'EX2', -- Key used to use this version, should it be locked. Leave as '' to unlock this version.
	Notes = {
		Comments = { -- Addition/implementation, removal, and more comments go here.
			'EXPERIMENTAL door "bounce" feature.',
		},
		Patches = { -- Patches (i.e. bug fixes, important adjustments, etc.) go here.
			
		},
	},

}