return {

	Name = '2026.01.19.1', -- Name of the version (yyyy.mm.dd.canidate_#)
	Description = 'January 19th, 2026 release. Candidate 1', -- Describe the version's name here
	VersionNumber = 15, -- The specified version number for this release
	Key = '', -- Key used to use this version, should it be locked. Leave as '' to unlock this version.
	Notes = {
		Comments = { -- Addition/implementation, removal, and more comments go here.
			'Improved door safety.',
			'Adds an assignable ID for your elevator.'
		},
		Patches = { -- Patches (i.e. bug fixes, important adjustments, etc.) go here.
			
		},
	},

}