return {

	Name = '2025.08.07.1', -- Name of the version (yyyy.mm.dd.release candiate #)
	Description = 'August 7th, 2025 release, candidate 1', -- Describe the version's name here
	VersionNumber = 8, -- The specified version number for this release
	Key = '', -- Key used to use this version, should it be locked. Leave as '' to unlock this version.
	Notes = {
		Comments = { -- Miscallaneous comments go here.
			'First production release.',
		},
		Patches = { -- Patches (i.e. bug fixes, important adjustments, etc.) go here.
			''
		},
	},

}