return {

	Name = 'MV2_2024_2', -- Name of the version (MV2_yyyy_release candiate #)
	Description = 'December 26th, 2024 release.', -- Describe the version's name here
	VersionNumber = 4, -- The specified version number for this release
	Key = '', -- Key used to use this version, should it be locked. Leave as '' to unlock this version.
	Notes = {
		Comments = { -- Miscallaneous comments go here.
			'',
		},
		Patches = { -- Patches (i.e. bug fixes, important adjustments, etc.) go here.
			'Adds time-out to prevent buttons from being permanetely stuck, should that happen.',
		},
	},

}