return {

	Name = '2025.07.25.1', -- Name of the version (yyyy.mm.dd.release candiate #)
	Description = 'July 25th, 2025 release, candidate 1', -- Describe the version's name here
	VersionNumber = 7, -- The specified version number for this release
	Key = '', -- Key used to use this version, should it be locked. Leave as '' to unlock this version.
	Notes = {
		Comments = { -- Miscallaneous comments go here.
			'Implements a BindableFunction to allow for call invocation with the ability to have data returned.',
		},
		Patches = { -- Patches (i.e. bug fixes, important adjustments, etc.) go here.
			''
		},
	},

}