return {

	Name = '2025.08.07.1', -- Name of the version (yyyy.mm.dd.canidate_#)
	Description = 'August 7th, 2025 release of MXV2. Candidate 1', -- Describe the version's name here
	VersionNumber = 1, -- The specified version number for this release
	Key = '', -- Key used to use this version, should it be locked. Leave as '' to unlock this version.
	Notes = {
		Comments = { -- Addition/implementation, removal, and more comments go here.
			'The first Production release of Modulux V2.'
		},
		Patches = { -- Patches (i.e. bug fixes, important adjustments, etc.) go here.
			
		},
	},

}