return {

	Name = '2025.11.04.1', -- Name of the version (yyyy.mm.dd.canidate_#)
	Description = 'November 4th, 2025 release of MXV2. Candidate 1', -- Describe the version's name here
	VersionNumber = 13, -- The specified version number for this release
	Key = '', -- Key used to use this version, should it be locked. Leave as '' to unlock this version.
	Notes = {
		Comments = { -- Addition/implementation, removal, and more comments go here.
			'Adds pre-start; allows for the car to begin to move when the inner doors reach its maximum safety tolerance.'
		},
		Patches = { -- Patches (i.e. bug fixes, important adjustments, etc.) go here.
			'Fixed & improved door safety.'
		},
	},

}